- name: Ensure logrotate is installed
  package:
    name: logrotate
    state: present

- name: Ensure /etc/logrotate.d directory exists
  file:
    path: /etc/logrotate.d
    state: directory
    mode: "0755"

- name: Deploy logrotate config for MongoDB
  template:
    src: mongodb.j2
    dest: /etc/logrotate.d/mongodb
    mode: "0644"
