- name: Gather installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Ensure logrotate is installed
  ansible.builtin.package:
    name: logrotate
    state: present
  when: logrotate_mongodb_enabled
  become: true

- name: Ensure /etc/logrotate.d directory exists
  ansible.builtin.file:
    path: /etc/logrotate.d
    state: directory
    mode: "0755"
  when: logrotate_mongodb_enabled

- name: Deploy logrotate config for MongoDB
  ansible.builtin.template:
    src: mongodb.j2
    dest: /etc/logrotate.d/mongodb
    mode: "0644"
  when: logrotate_mongodb_enabled
